=== olegchursin/parallel/content/schemas/places.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "schemaVersion": {
      "type": "number",
      "const": 1
    },
    "id": {
      "type": "string",
      "pattern": "^plc_\\d{6}$"
    },
    "preferredName": {
      "type": "string"
    },
    "placeType": {
      "type": "string",
      "const": "historical-place"
    },
    "regionIds": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "sourceRefs": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^src_\\d{6}$"
      }
    },
    "modernLocator": {
      "type": "string"
    }
  },
  "required": [
    "schemaVersion",
    "id",
    "preferredName",
    "placeType",
    "regionIds",
    "sourceRefs",
    "modernLocator"
  ],
  "additionalProperties": false
}

=== olegchursin/parallel/content/places/plc_000150.json
{
  "schemaVersion": 1,
  "id": "plc_000150",
  "preferredName": "International sequencing consortium",
  "placeType": "historical-place",
  "regionIds": [
    "global"
  ],
  "sourceRefs": [
    "src_000130"
  ],
  "modernLocator": "China, France, Germany, Japan, United Kingdom and United States"
}
